### ISSUE TITLE
bower.json: Why 'private'

### ISSUE THREAD

**Issue by ankon** [PolymerElements/paper-button#104]
I noticed this just now: why does `bower.json` actually specify `private`?

**Comment by keanulee** [comment]
@ankon It's because we don't want to be in the bower registry. See https://github.com/Polymer/polymer/issues/1245#issuecomment-79179300

**Comment by ankon** [comment]
Thank you, that makes a lot of sense.

**Comment by marcus7777** [comment]
https://blog.polymer-project.org/announcements/2016/02/16/2016-roadmap/
...
Goals:

Accelerate Polymer + Community engagement
Tighten the core Polymer team and community feedback loop - better evolve Polymer as the community evolves
Publish all elements to npm and bower
...

**Comment by marcus7777** [comment]
why not simply flip private: false on all your repos it a step?

**Comment by notwaldorf** [comment]
@marcus7777 Because then people (not us) could publish some, but not all of the repos to bower, and it would be a fair assumption that `paper-ripple` was also published and maintained by this team, but that assumption is incorrect. Since we don't have an answer that fixes all the elements, we can't just flip this boolean.

**Comment by marcus7777** [comment]
dropping it

**Comment by marcus7777** [comment]
thanks
