### ISSUE TITLE
paper-button page on webcomponents.org is broken

### ISSUE THREAD

**Issue by hidai** [PolymerElements/paper-button#176]
### Description
Seems like the paper-button page is broken, but other elements are ok.

### Expected outcome
* Version number should be v2.2 or so
* Demo link is available

### Actual outcome
* Version number is v0.0.4
* Demo link is not available.

### Live Demo
https://www.webcomponents.org/element/@polymer/paper-button
https://www.webcomponents.org/element/PolymerElements/paper-button

### Steps to reproduce
1. Open the link.
2. See page contents are wrong.

### Browsers Affected
I only tested on Chrome OS 66.

**Comment by keanulee** [comment]
We're in the progress of releasing 3.x versions of our elements to NPM, and part of that change is adding NPM support to webcomponents.org. The 0.0.4 release is the latest non-prerelease version on NPM - [3.0.0-pre.19](https://www.webcomponents.org/element/@polymer/paper-button/3.0.0-pre.19) is the latest prerelease version which we hope to release soon (demo is broken on webcomponents.org because the [README demo](https://raw.githubusercontent.com/PolymerElements/paper-button/__auto_generated_3.0_preview/README.md) hasn't been updated for 3.x). Please bear with us during this transition.

**Comment by hidai** [comment]
I see. But we're still using Polymer 2 and can't pay resources for migration of 3.x shortly. Webcomponents.org is important tool for us to see specs and demos before using components. I think it should serve 2.x contents as well for the most Polymer developers who are still using 2.x. Is it difficult to take 2.x pages back to see specs and demos?

**Comment by masonlouchart** [comment]
Please, publish the v2.1.1 on NPM, it starts to be ridiculous. If it's so difficult to publish on NPM stop use it. Sorry for my fucking feeling but I'm using Polymer since the v0.5 and now I feel like the Polymer Team thrown everything to join the JS community. You could have at least avoid regression.

**Comment by keanulee** [comment]
We are not planning to publish 2.x versions of elements on NPM, one technical reason (among others) being NPM doesn't guarantee flat installation that HTML imports needs. 3.x elements will use ES modules with package names instead.

**Comment by hidai** [comment]
Just realized that there is a "View Bower docs" link on the page. This is what I wanted. Closing.

![image](https://user-images.githubusercontent.com/792102/41455988-1af31964-70ba-11e8-8038-9a7e20ccd20d.png)

**Comment by masonlouchart** [comment]
Completely understandable @keanulee.

Nice catch @hidai さん! 👍
